#!/bin/bash
echo "🔧 Setting up prodtools environment..."

# Add prodtools and test directories to PATH
PRODTOOLS_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
export PATH="$PRODTOOLS_DIR:$PATH"

echo "📁 Added prodtools directory to PATH: $PRODTOOLS_DIR"
echo "🚀 You can now run all commands directly:"
echo "   Production tools:"
echo "     - json2jobdef"
echo "     - fcldump"
echo "     - runjobdef"
echo "     - runfcl"
echo "     - mkidxdef"
echo "     - jobdef"
echo "     - jsonexpander"
echo ""
echo "💡 Usage examples:"
echo "   Production tools:"
echo "     muse setup SimJob"
echo "     json2jobdef --json config.json --index 0"
echo "     ./jobdef --setup /cvmfs/mu2e.opensciencegrid.org/Musings/SimJob/MDC2020av/setup.sh \\"
echo "         --dsconf MDC2020av --desc ExtractedCRY --dsowner mu2e --embed template.fcl"
echo "     fcldump --dataset cnf.mu2e.RPCInternalPhysical.MDC2020az.tar"
echo "     runjobdef --jobdefs jobdefs.txt --dry-run"
echo "     runfcl --fcl template.fcl --nevents 1000 --dry-run"
